version: "3.8"

services:
  taskengine.webapi:
    build:
      context: ./TaskEngine.WebAPI
      dockerfile: TaskEngine.WebAPI/Dockerfile
    image: taskenginewebapi
    container_name: taskengine-webapi
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
      RABBITMQ_URL: "rabbitmq"
    entrypoint: ["./wait-for-it.sh", "rabbitmq:5672", "--", "./wait-for-it.sh", "mongodb:27017", "--", "dotnet", "TaskEngine.WebAPI.dll"]

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
